--- #YAML:1.0
name:               File-KeePass
version:            0.03
abstract:           Interface to KeePass V1 database files
author:
    - Paul Seamons
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::Rijndael:  1.0
    Digest::SHA:      1.0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
